### PR TITLE
fix bug verification bypass

### LINKED ISSUE #13: DataEntry Bug
In the DataEntry Tab, before the user completely fill in all the input data, User shouldn't be able to access Verification Process. However, there a bug that allow the User to access the Verification without yet fill out all the data or complete the Data entry process.

### PR DESCRIPTION
**Pull request by StoicNeutron**
close #13

### CODE REVIEW

File: src/main/java/com/attorneyrequest/data_entry/DataEntryGUI.java [hunk 1]
```diff
@@ -159,11 +159,11 @@ public void actionPerformed(java.awt.event.ActionEvent evt) {
             }
         });
 
-        // aptSuit lable
+        // states
```
Comment (StoicNeutron) [inline src/main/java/com/attorneyrequest/data_entry/DataEntryGUI.java:162]: Reviewed
